{application,microservicio2,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"microservicio2"},
              {modules,['Elixir.Microservicio2',
                        'Elixir.Microservicio2.Application']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Microservicio2.Application',[]}}]}.
